[features]
seeds = false
skip-lint = false
[programs.localnet]
wsos_calculator = "4HqhJGdvXPnPNpJNwCQ65zuXk28jbywyW8YBNprAifdN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mayankjha/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
